notifications:
  email:
    recipients:
      - dev@rocketmq.apache.org
  on_success: change
  on_failure: always

language: java

jdk:
  - openjdk8
  - oraclejdk8

matrix:
  include:
  # On OSX, run with default JDK only.
  # - os: osx
  # On Linux, run with specific JDKs only.
  - os: linux

before_install:
  - echo 'MAVEN_OPTS="$MAVEN_OPTS -Xmx1024m -XX:MaxPermSize=512m -XX:+BytecodeVerificationLocal"' >> ~/.mavenrc
  - cat ~/.mavenrc

script:
  - travis_retry mvn -B clean apache-rat:check
  - travis_retry mvn -B package jacoco:report coveralls:report

after_success:
  - mvn clean install -Pit-test
  - mvn sonar:sonar -Psonar-apache
