brokerClusterName=DefaultCluster
brokerName=broker-c
brokerId=0
deleteWhen=04
fileReservedTime=480
brokerRole=SYNC_MASTER
flushDiskType=ASYNC_FLUSH

storePathRootDir=/app/store-c
storePathCommitLog=/app/store-c/commitlog

messageDelayLevel=1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 40m 50m 1h 2h 6h

autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
maxTransferCountOnMessageInMemory=512

listenPort=10910
brokerIP1=192.168.0.73
brokerIP2=192.168.0.73
