brokerClusterName=DefaultCluster
brokerName=broker-d
brokerId=1
deleteWhen=04
fileReservedTime=168
brokerRole=SLAVE
flushDiskType=ASYNC_FLUSH

storePathRootDir=/app/store-d-s
storePathCommitLog=/app/store-d-s/commitlog
messageDelayLevel=1s 5s 10s 30s 1m 2m 3m 4m 5m 6m 7m 8m 9m 10m 20m 30m 40m 50m 1h 2h 6h
autoCreateTopicEnable=true
autoCreateSubscriptionGroup=true
listenPort=10930
traceTopicEnable=true
#?????????????200ms
waitTimeMillsInSendQueue=500

maxTransferBytesOnMessageInMemory=83886080
maxTransferCountOnMessageInMemory=10240
maxTransferBytesOnMessageInDisk=262144
maxTransferCountOnMessageInDisk=64